name: fashionapp
description: "A new Flutter project."
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  flutter_dotenv: ^5.2.1
  flutter_vector_icons: ^2.0.0
  cross_connectivity: ^3.3.0
  google_fonts: ^6.2.1
  flutter_rating_bar: ^4.0.1
  shimmer: ^3.0.0
  provider: ^6.1.5
  flutter_image_slideshow: ^0.1.6
  cached_network_image: ^3.4.1
  flutter_svg: ^2.2.0
  flutter_hooks: ^0.21.2
  flutter_staggered_grid_view: ^0.7.0
  go_router: ^16.0.0
  get_storage: ^2.1.1
  page_view_dot_indicator: ^2.3.0
  flutter_otp_text_field: ^1.5.1+1
  webview_flutter_android: ^4.9.1
  webview_flutter: ^4.13.0
  webview_flutter_wkwebview: ^3.23.0
  google_maps_flutter: ^2.12.3
  get_time_ago: ^2.3.1
  firebase_messaging: ^15.2.7
  # flutter_local_notifications: ^19.3.0
  firebase_core: ^3.14.0
  http: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:

  
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    # - images/a_dot_burr.jpeg
    # - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
